# Generated by Django 3.2.4 on 2021-06-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacciapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='map',
            new_name='addMap',
        ),
    ]
