# Generated by Django 3.2.4 on 2021-06-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacciapp', '0003_alter_slot_addmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
