# Generated by Django 3.2.4 on 2021-06-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacciapp', '0004_slot_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Completed', 'Completed')], default='Pending', max_length=200, null=True),
        ),
    ]
